Run('"C:\Program Files\Internet Explorer\iexplore.exe" "https://download.mozilla.org/?product=firefox-nightly-stub&os=win&lang=en-US"')
_WinWaitActivate("Downloads weergeven - Internet Explorer","")
MouseClick("left", 447,137,1)
_WinWaitActivate("Default Browser","")
Send("{TAB}{SPACE}")
_WinWaitActivate("Nightly Start Page - Nightly","")
Send("{ALTDOWN}{F4}{ALTUP}")
_WinWaitActivate("Downloads weergeven - Internet Explorer","")
MouseClick("left",563,447,1)
